### ISSUE TITLE
feat: Add Xblock completion mode to course sink

### ISSUE THREAD

**Issue by bmtcril** [openedx/openedx-event-sink-clickhouse#48]
In order to know which Xblocks have the ability to be completed before any student actually triggers a completion on them, we would like to have the "completion mode" for the blocks sent to the course sink: https://github.com/openedx/XBlock/blob/3304375ee47d428db769578bd00c079a6c75d015/xblock/completable.py#L10

This can go in the JSON blob and be parsed out downstream, but will allow us to better display completion rates early in the course.

**Comment by mavidser** [comment]
Hi @bmtcril. Does #49 close this?

**Comment by Ian2012** [comment]
@mavidser yes, it does
