### ISSUE TITLE
Add management command to bulk dump courses

### ISSUE THREAD

**Issue by bmtcril** [openedx/openedx-event-sink-clickhouse#5]
Functionality should match the existing coursegraph command, but with an option to limit the number of courses dumped at a time to prevent site outages or Celery overflow:

https://github.com/openedx/edx-platform/blob/1bf8af5f721bb0ccfb6f8882b3e24d2521e62b25/cms/djangoapps/coursegraph/management/commands/dump_to_neo4j.py#L32

**Comment by bmtcril** [comment]
#7 should solve this

**Comment by Ian2012** [comment]
can be closed now
